2021-03-13 22:31:14,896 ERROR: Exception on /index [GET] [in c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\BrandonMa\Python projects\webdev\jobquest-flask\app\main\routes.py", line 31, in index
    next_url = url_for('index', page=postings.next_num) if postings.has_next else None
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index' with values ['page']. Did you mean 'main.index' instead?
2021-03-13 22:31:16,184 ERROR: Exception on /index [GET] [in c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\BrandonMa\Python projects\webdev\jobquest-flask\app\main\routes.py", line 31, in index
    next_url = url_for('index', page=postings.next_num) if postings.has_next else None
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index' with values ['page']. Did you mean 'main.index' instead?
2021-03-13 22:31:38,845 INFO: App startup [in C:\Users\BrandonMa\Python projects\webdev\jobquest-flask\app\__init__.py:38]
2021-03-13 22:31:40,967 ERROR: Exception on /index [GET] [in c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\BrandonMa\Python projects\webdev\jobquest-flask\app\main\routes.py", line 31, in index
    next_url = url_for('index', page=postings.next_num) if postings.has_next else None
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\brandonma\python projects\webdev\jobquest-flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index' with values ['page']. Did you mean 'main.index' instead?
